# Generated by Django 5.0.3 on 2024-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voters_name', models.CharField(blank=True, max_length=200, null=True)),
                ('politician_name', models.CharField(blank=True, max_length=200, null=True)),
                ('politician_position', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
